sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t telltalemajora/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true telltalemajora/react-test npm test

after_success:
  - docker build -t telltalemajora/multi-client ./client
  - docker build -t telltalemajora/multi-nginx ./nginx
  - docker build -t telltalemajora/multi-server ./server
  - docker build -t telltalemajora/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# push built images above to docker hub
  - docker push telltalemajora/multi-client
  - docker push telltalemajora/multi-nginx
  - docker push telltalemajora/multi-server
  - docker push telltalemajora/multi-worker

# deploy configuration for aws 
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-899240869859
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY